In [1]:
import pandas as pd
import numpy as np

In [2]:
count_file = 'counts.txt'
gene_id_product_file = 'gene_id_product.tsv'

In [3]:
df = pd.read_table(count_file, index_col=0, skiprows=1)

In [4]:
df

,Chr,Start,End,Strand,Length,SRR453566.sorted.bam,SRR453567.sorted.bam,SRR453568.sorted.bam,SRR453569.sorted.bam,SRR453570.sorted.bam,SRR453571.sorted.bam
Geneid,,,,,,,,,,,
gene_0001,NC_001133.9,1807,2169,-,363,0,2,6,0,0,1
gene_0002,NC_001133.9,2480,2707,+,228,0,0,0,0,0,0
gene_0003,NC_001133.9,7235,9016,-,1782,0,0,0,0,0,0
gene_0004,NC_001133.9,11565,11951,-,387,0,0,0,0,0,0
gene_0005,NC_001133.9,12046,12426,+,381,2,8,10,6,7,18
...,...,...,...,...,...,...,...,...,...,...,...
gene_6440,NC_001224.1,77431,77505,+,75,0,0,0,0,0,0
gene_6441,NC_001224.1,78089,78162,-,74,0,0,0,0,0,0
gene_6442,NC_001224.1,78533,78608,+,76,0,0,0,0,0,0
gene_6444,NC_001224.1,85035,85112,+,78,0,0,0,0,0,0
gene_6445,NC_001224.1,85295,85777,+,483,0,0,0,1,0,0

In [5]:
df.shape

(6420, 11)

In [6]:
df.columns

Index(['Chr', 'Start', 'End', 'Strand', 'Length', 'SRR453566.sorted.bam',
       'SRR453567.sorted.bam', 'SRR453568.sorted.bam', 'SRR453569.sorted.bam',
       'SRR453570.sorted.bam', 'SRR453571.sorted.bam'],
      dtype='object')

In [9]:
names = {'SRR453566.sorted.bam': 'batch_1', 'SRR453567.sorted.bam': 'batch_2', 'SRR453568.sorted.bam': 'batch_3',
'SRR453569.sorted.bam': 'cheomstat_1', 'SRR453570.sorted.bam': 'cheomstat_2', 'SRR453571.sorted.bam': 'cheomstat_3'}

df = df.rename(mapper=names, axis=1)

In [10]:
df

,Chr,Start,End,Strand,Length,batch_1,batch_2,batch_3,cheomstat_1,cheomstat_2,cheomstat_3
Geneid,,,,,,,,,,,
gene_0001,NC_001133.9,1807,2169,-,363,0,2,6,0,0,1
gene_0002,NC_001133.9,2480,2707,+,228,0,0,0,0,0,0
gene_0003,NC_001133.9,7235,9016,-,1782,0,0,0,0,0,0
gene_0004,NC_001133.9,11565,11951,-,387,0,0,0,0,0,0
gene_0005,NC_001133.9,12046,12426,+,381,2,8,10,6,7,18
...,...,...,...,...,...,...,...,...,...,...,...
gene_6440,NC_001224.1,77431,77505,+,75,0,0,0,0,0,0
gene_6441,NC_001224.1,78089,78162,-,74,0,0,0,0,0,0
gene_6442,NC_001224.1,78533,78608,+,76,0,0,0,0,0,0
gene_6444,NC_001224.1,85035,85112,+,78,0,0,0,0,0,0
gene_6445,NC_001224.1,85295,85777,+,483,0,0,0,1,0,0